/**
 * Function-level binary diff — the step from "this image has CVE-X" to "here is the code that changed".
 *
 * The SBOM/CVE track tells you a component is vulnerable and the version-comparison track tells you a finding
 * disappeared between two releases. Neither localizes anything: you still cannot point at the function the vendor
 * touched. This provider pairs binaries across two extracted rootfs by path, fingerprints every function on both
 * sides, matches them, and reports the ones that changed — the candidate set a reverser reads to find the patch.
 *
 * The honesty problem here is specific and severe, and it shapes the whole design:
 *
 *  - **A toolchain bump rewrites everything.** Recompile the same source with a different GCC and virtually every
 *    function's size, block count and instruction count move. Emitting that as "412 changed functions, one is the
 *    patch" would be a candidate list with no information in it, dressed as analysis. So when the changed fraction
 *    crosses a threshold the verdict is `recompiled`, the function list is WITHHELD, and the reason says the diff
 *    cannot localize anything. A small diff against an otherwise byte-stable build is the only case where the
 *    candidate set means something.
 *  - **Firmware binaries are stripped.** Internal functions come back as `fcn.00400abc`, whose name encodes the
 *    ADDRESS — it changes whenever anything before it in the binary moves, so name-matching them is worse than
 *    useless. Those are matched structurally instead, and ONLY on a fingerprint that is unique on both sides;
 *    an ambiguous fingerprint is reported as unmatchable rather than paired by guesswork.
 *  - **A changed function is a fact, not a fix.** "This function's structure differs between the two builds" is
 *    `static_confirmed`. "This is the security patch" is an inference the diff cannot make, and does not.
 *
 * Everything in this module is pure and unit-tested; the runner (funcdiff-run.ts) supplies the radare2 output.
 */
import type { FindingDraft } from '../findings-normalize.js';

/** One function's structural fingerprint, as radare2's `aflj` reports it. */
export interface FuncSig {
  name: string;
  offset: number;
  size: number;
  /** Basic-block count. */
  nbbs: number;
  /** Cyclomatic complexity. */
  cc: number;
  ninstrs: number;
  edges: number;
}

export interface FuncDiff {
  name: string;
  status: 'changed' | 'added' | 'removed';
  /** How the fingerprint moved, for a changed function. */
  delta?: { size: number; nbbs: number; cc: number; ninstrs: number };
  a?: FuncSig;
  b?: FuncSig;
}

export type DiffVerdict = 'identical' | 'patched' | 'recompiled' | 'incomparable';

export interface BinaryDiff {
  path: string;
  verdict: DiffVerdict;
  matched: number;
  changed: number;
  added: number;
  removed: number;
  /** Functions whose fingerprint was ambiguous on one side, so pairing them would have been guesswork. */
  unmatchable: number;
  /** Withheld entirely on a `recompiled` verdict — see the module note. */
  functions: FuncDiff[];
  reason: string;
}

/**
 * Above this fraction of matched functions changing, the two builds are not "the same program with a patch" and
 * the diff cannot localize anything. Deliberately generous: a real security patch touches a handful of functions,
 * so anything approaching half the binary is a rebuild, not a fix.
 */
export const RECOMPILE_THRESHOLD = 0.4;

/** Below this many matched functions, the ratio is statistical noise and the verdict cannot be trusted either way. */
export const MIN_MATCHED_FOR_RATIO = 10;

/** Only the top few changed functions are worth carrying into a finding; the rest stay in the structured result. */
export const FINDING_FUNC_CAP = 12;

/**
 * Pure: is this name radare2's autogenerated placeholder rather than a real symbol?
 *
 * `fcn.00400abc` / `sub.400abc` encode the function's ADDRESS. Any change earlier in the binary shifts every later
 * address, so matching two builds on these names would pair unrelated functions and report the whole binary as
 * changed. They are matched structurally instead.
 */
export function isSyntheticName(name: string): boolean {
  return /^(fcn|sub|loc|unk)[._]/i.test(name) || /^0x[0-9a-f]+$/i.test(name);
}

/** Pure: normalize radare2's `aflj` array into fingerprints, dropping entries too malformed to compare. */
export function parseFunctions(raw: unknown): FuncSig[] {
  if (!Array.isArray(raw)) return [];
  const out: FuncSig[] = [];
  for (const r of raw) {
    const e = (r ?? {}) as Record<string, unknown>;
    const num = (k: string): number => (typeof e[k] === 'number' ? (e[k] as number) : 0);
    const name = typeof e.name === 'string' ? e.name : '';
    if (!name) continue;
    out.push({
      name,
      offset: num('offset'),
      size: num('size'),
      nbbs: num('nbbs'),
      cc: num('cc'),
      ninstrs: num('ninstrs'),
      edges: num('edges'),
    });
  }
  return out;
}

/** The structural key two stripped functions must share to be considered the same function. */
function structuralKey(f: FuncSig): string {
  return `${f.nbbs}:${f.cc}:${f.ninstrs}:${f.edges}`;
}

/** Did the fingerprint move at all? Size alone shifts with alignment, so the shape metrics matter more. */
function differs(a: FuncSig, b: FuncSig): boolean {
  return a.size !== b.size || a.nbbs !== b.nbbs || a.cc !== b.cc || a.ninstrs !== b.ninstrs || a.edges !== b.edges;
}

export interface MatchResult {
  pairs: { a: FuncSig; b: FuncSig }[];
  onlyA: FuncSig[];
  onlyB: FuncSig[];
  /** Stripped functions whose structural key was not unique on both sides — honestly unpaired. */
  ambiguous: FuncSig[];
}

/**
 * Pure: match functions across two builds.
 *
 * Two passes, strongest evidence first. Real symbol names are matched directly — a name is the vendor's own
 * identity for the function and survives a rebuild. What remains is stripped, so it is matched on a structural
 * fingerprint, and ONLY where that fingerprint occurs exactly once on each side: a binary contains many trivial
 * 1-block functions with identical shapes, and pairing those arbitrarily would manufacture "changes" out of an
 * ordering coincidence. Ambiguous ones are counted and reported, never guessed.
 */
export function matchFunctions(a: FuncSig[], b: FuncSig[]): MatchResult {
  const pairs: { a: FuncSig; b: FuncSig }[] = [];
  const usedA = new Set<FuncSig>();
  const usedB = new Set<FuncSig>();

  const byNameB = new Map<string, FuncSig>();
  for (const f of b) if (!isSyntheticName(f.name)) byNameB.set(f.name, f);
  for (const fa of a) {
    if (isSyntheticName(fa.name)) continue;
    const fb = byNameB.get(fa.name);
    if (!fb || usedB.has(fb)) continue;
    pairs.push({ a: fa, b: fb });
    usedA.add(fa);
    usedB.add(fb);
  }

  // Only STRIPPED leftovers go to the structural pass. A function that carries a real symbol and found no
  // same-named counterpart is genuinely added or removed — pairing `sym.gone` with `sym.fresh` because they
  // happen to share a shape would invent a match the names explicitly contradict.
  const restA = a.filter((f) => !usedA.has(f) && isSyntheticName(f.name));
  const restB = b.filter((f) => !usedB.has(f) && isSyntheticName(f.name));

  const countKeys = (fs: FuncSig[]): Map<string, FuncSig[]> => {
    const m = new Map<string, FuncSig[]>();
    for (const f of fs) {
      const k = structuralKey(f);
      const list = m.get(k);
      if (list) list.push(f);
      else m.set(k, [f]);
    }
    return m;
  };
  const keysA = countKeys(restA);
  const keysB = countKeys(restB);
  const ambiguous: FuncSig[] = [];

  for (const [key, listA] of keysA) {
    const listB = keysB.get(key);
    if (!listB) continue;
    if (listA.length === 1 && listB.length === 1) {
      const fa = listA[0] as FuncSig;
      const fb = listB[0] as FuncSig;
      pairs.push({ a: fa, b: fb });
      usedA.add(fa);
      usedB.add(fb);
    } else {
      // Same shape, several candidates: pairing them would be arbitrary, so neither side is claimed.
      ambiguous.push(...listA);
      for (const f of listA) usedA.add(f);
      for (const f of listB) usedB.add(f);
    }
  }

  return {
    pairs,
    onlyA: a.filter((f) => !usedA.has(f)),
    onlyB: b.filter((f) => !usedB.has(f)),
    ambiguous,
  };
}

/**
 * Pure: turn a match into a verdict.
 *
 * The verdict is the point of this module. `patched` licenses a reverser to read the listed functions; `recompiled`
 * says the two builds differ everywhere and the list would be noise, so it is withheld rather than shown with a
 * caveat nobody reads. `incomparable` covers too little matched surface to judge either way.
 */
export function classifyDiff(path: string, m: MatchResult): BinaryDiff {
  const changedPairs = m.pairs.filter((p) => differs(p.a, p.b));
  const matched = m.pairs.length;
  const base: Omit<BinaryDiff, 'verdict' | 'functions' | 'reason'> = {
    path,
    matched,
    changed: changedPairs.length,
    added: m.onlyB.length,
    removed: m.onlyA.length,
    unmatchable: m.ambiguous.length,
  };

  const functions: FuncDiff[] = [
    ...changedPairs.map(
      (p): FuncDiff => ({
        name: p.b.name,
        status: 'changed',
        delta: {
          size: p.b.size - p.a.size,
          nbbs: p.b.nbbs - p.a.nbbs,
          cc: p.b.cc - p.a.cc,
          ninstrs: p.b.ninstrs - p.a.ninstrs,
        },
        a: p.a,
        b: p.b,
      }),
    ),
    ...m.onlyB.filter((f) => !isSyntheticName(f.name)).map((f): FuncDiff => ({ name: f.name, status: 'added', b: f })),
    ...m.onlyA
      .filter((f) => !isSyntheticName(f.name))
      .map((f): FuncDiff => ({ name: f.name, status: 'removed', a: f })),
  ];
  // Smallest structural movement first: a security patch is usually a bounds check or a length change, not a
  // rewritten function, so the tightest deltas are the ones worth reading first.
  functions.sort((x, y) => Math.abs(x.delta?.ninstrs ?? 999) - Math.abs(y.delta?.ninstrs ?? 999));

  if (matched === 0) {
    return {
      ...base,
      verdict: 'incomparable',
      functions: [],
      reason:
        'No function could be matched across the two builds — nothing here is a comparison. Either the binaries ' +
        'are unrelated, or both are stripped in a way that leaves no unique structural fingerprint to pair on.',
    };
  }
  if (changedPairs.length === 0 && m.onlyA.length === 0 && m.onlyB.length === 0) {
    return {
      ...base,
      verdict: 'identical',
      functions: [],
      reason: `All ${matched} matched function(s) are structurally identical — no code change is visible at this granularity.`,
    };
  }
  if (matched < MIN_MATCHED_FOR_RATIO) {
    return {
      ...base,
      verdict: 'incomparable',
      functions,
      reason: `Only ${matched} function(s) matched, which is too little surface to tell a patch from a rebuild. The listed differences are real, but they are not evidence of a targeted change.`,
    };
  }

  const ratio = changedPairs.length / matched;
  if (ratio > RECOMPILE_THRESHOLD) {
    return {
      ...base,
      verdict: 'recompiled',
      // Withheld deliberately: a list this large has no localizing power, and showing it with a caveat invites
      // exactly the reading the caveat forbids.
      functions: [],
      reason: `${changedPairs.length} of ${matched} matched functions (${Math.round(ratio * 100)}%) changed — that is a REBUILD, not a patch. A different compiler or flags moves nearly every function, so no candidate set is offered: it would be noise presented as analysis. Diff a closer pair of versions to localize a change.`,
    };
  }

  return {
    ...base,
    verdict: 'patched',
    functions,
    reason: `${changedPairs.length} of ${matched} matched functions (${Math.round(ratio * 100)}%) changed, with ${m.onlyB.length} added and ${m.onlyA.length} removed — a small, localized delta against an otherwise stable build. These are the functions to read; which one (if any) is a security fix is not something this diff can tell you.`,
  };
}

/**
 * Pure: findings for one binary's diff.
 *
 * Only `patched` produces a candidate list, and it is phrased as a code FACT: these functions differ between the
 * two builds. `recompiled` still produces a finding, because "we compared and could not localize" is a result the
 * operator needs — silence there would read as "no change found".
 */
export function buildFuncDiffFindings(diff: BinaryDiff, older: string, newer: string): FindingDraft[] {
  if (diff.verdict === 'identical') return [];

  if (diff.verdict === 'patched') {
    const named = diff.functions.slice(0, FINDING_FUNC_CAP);
    return [
      {
        kind: 'function-diff-candidate',
        title: `${diff.path}: ${diff.changed} function(s) changed between ${older} and ${newer}`,
        severity: 'info',
        proofState: 'static_confirmed',
        evidence: {
          binary: diff.path,
          older,
          newer,
          matched: diff.matched,
          changed: diff.changed,
          added: diff.added,
          removed: diff.removed,
          unmatchable: diff.unmatchable,
          functions: named.map((f) => ({ name: f.name, status: f.status, delta: f.delta })),
          ...(diff.functions.length > named.length ? { furtherFunctions: diff.functions.length - named.length } : {}),
        },
        rationale: `${diff.reason} The changed functions are a code fact read from both builds' control-flow structure. Whether any of them is the fix for a specific CVE is an inference this does not make — read them, and correlate with the advisory.`,
      },
    ];
  }

  return [
    {
      kind: 'function-diff-inconclusive',
      title: `${diff.path}: the two builds differ too broadly to localize a change`,
      severity: 'info',
      proofState: 'needs_runtime_reproduction',
      evidence: {
        binary: diff.path,
        older,
        newer,
        verdict: diff.verdict,
        matched: diff.matched,
        changed: diff.changed,
        unmatchable: diff.unmatchable,
      },
      rationale: `${diff.reason} Recorded so this reads as "compared, could not localize" rather than as "no change found" — those are different results and only one of them is reassuring.`,
    },
  ];
}
